### ISSUE TITLE
Collaborative Comp, Explore Data, Share Knowledge section 

### ISSUE THREAD

**Issue by jrhea** [arithm3tica/landing-page#10]
This is ugly as hell.  We paid thousands of dollars for styling and we destroy everything good about it by showing this section. 

![image](https://user-images.githubusercontent.com/5555162/43552036-b93c932a-95ae-11e8-8c08-00c0b55a7700.png)

**Comment by ryangoree** [comment]
That's a screenshot of the subscription again, but the title mentions sections on the page. Is the "ugly" comment about the subscription confirmation or the page?

**Comment by jrhea** [comment]
Ok sorry...I fixed the screenshot.  Also, the text is total dogshit.  I think we can remove all that and replace it with:

> Arithmetica is an open source, decentralized, network of computers powered by Ethereum.  This gives researchers access to free computational power and the rest of us an opportunity to contribute by simply visiting a website.

This is, by far, the message that resonated with twitter users the most

**Comment by jrhea** [comment]
I think that solves the "what is arithmetica" problem that we were trying to answer with 3 paragraphs of text

**Comment by jrhea** [comment]
Commit 849168bc300a3e5f148b1aa6801ba7ea217ca51a resolves this issue
