### ISSUE TITLE
Upload a usable photo

### ISSUE THREAD

**Issue by jrhea** [arithm3tica/landing-page#8]
The goofy photo was funny at first, but we want to make sure that people know this is not a scam.

We need photos from everyone

**Comment by jrhea** [comment]
![00100sportrait_00100_burst20180203173809114_cover](https://user-images.githubusercontent.com/5555162/43553702-de98a6ca-95b5-11e8-8e44-ddf31c48df61.jpg)

**Comment by jrhea** [comment]
![img_20180110_121521](https://user-images.githubusercontent.com/5555162/43553980-5c940794-95b7-11e8-80e3-2cca1d0eba26.jpg)

**Comment by ryangoree** [comment]
I uploaded the images we from everyone. It still looks unprofessional. We might want to consider getting some nicer more consistent ones.

@jrhea, your's is the only one that looks like it was taken with a decent camera, but it's still a little close.

**Comment by jrhea** [comment]
Agreed, it looks really bad. @dangerousfood's head is cutoff

**Comment by jrhea** [comment]
@RyanG26 I cropped my photo and joe's and adjusted some css.  Still not perfect, but it looks ok.  Improvement, but we should probably plan this out

**Comment by jrhea** [comment]
Commit b54de4f01eef631353bb3df479389113559e96ac resolves this
